### ISSUE TITLE
Help with example files and error troubleshooting for md_dock

### ISSUE THREAD

**Issue by ddiem-ri-4D** [naisarg14/mutadock#1]
Dear @naisarg14 ,

Could you please provide an example of receptors.txt, ligands.txt, and config.txt files for the following command?
md_dock -r receptors.txt -l ligands.txt -c config.txt

Thank you very much!

Best regards,
Mỹ Diễm

**Comment by naisarg14** [comment]
[config.txt](https://github.com/user-attachments/files/18130161/config.txt)
[lig.txt](https://github.com/user-attachments/files/18130163/lig.txt)
[receptor.txt](https://github.com/user-attachments/files/18130210/receptor.txt)

Here are the examples for the input files. 
The files for ligand and receptor are just names of the files, one on each line. (It can be just the name if executing the script in the same folder or the path of the files)
The config file follows the same pattern as the config file for AutoDock Vina.

If you still face problems, share the files you are using.

**Comment by ddiem-ri-4D** [comment]
Hi @naisarg14,

I’m not sure if you’ve changed the source code, but when I run the following command, I get the error below:

> md_dock -r receptors.txt -l ligands.txt -c config.txt
> usage: np_dock [-h] [--config CONFIG] [--autosite AUTOSITE] [--quiet] [--ignore_existing] RECEPTOR LIGAND
> np_dock: error: unrecognized arguments: -r -l -c config.txt

> md_dock -h
> usage: np_dock [-h] [--config CONFIG] [--autosite AUTOSITE] [--quiet] [--ignore_existing] RECEPTOR LIGAND
> positional arguments:
> RECEPTOR Text File with all receptors
> LIGAND Text File with all ligands
> optional arguments:
> -h, --help show this help message and exit
> --config CONFIG Text File with all Vina Configuration Settings
> --autosite AUTOSITE PDB generated by autosite for binding site of protein.
> --quiet Run the Docking in quiet mode (default: False).
> --ignore_existing Run the Docking while ignoring existing files. All dockings will be performed again. (default: False).

Could you please check this for me?

I see that '**md_dock receptors.txt ligands.txt config.txt'** can run, but there are still some errors below. Could you please help me understand the cause of these errors?

> md_dock receptors.txt ligands.txt --config config.txt
> Receptor file: receptors.txt
> Ligands file: ligands.txt
> Config file: config.txt
> Found 0 completed receptor-ligand combinations. 1 combinations to be docked.
>   0%|                                                                                                                                                                                                                                                         | 0/1 [00:00<?, ?it/s]Docking the receptor /mnt/NAS_PROJECT/vol_Vyteam/vol_Diem/DATASM02/Docking/mutadock/2z4q.pdb to the ligand /mnt/NAS_PROJECT/vol_Vyteam/vol_Diem/DATASM02/Docking/mutadock/DB00317.sdf
> Docking for /mnt/NAS_PROJECT/vol_Vyteam/vol_Diem/DATASM02/Docking/mutadock/DB00317.sdf with /mnt/NAS_PROJECT/vol_Vyteam/vol_Diem/DATASM02/Docking/mutadock/2z4q.pdb
> Press Ctrl+D (EOFE Error) to skip this receptor-ligand combination.
> Preparing receptor /mnt/NAS_PROJECT/vol_Vyteam/vol_Diem/DATASM02/Docking/mutadock/2z4q.pdb
>   0%|                                                                                                                                                                                                                                                         | 0/1 [00:00<?, ?it/s]

>python3 /mnt/NAS_PROJECT/vol_Vyteam/vol_Diem/DATASM02/Docking/mutadock/src/docking/np_docking.py -r receptors.txt -l ligands.txt -c config.txt
>Receptor file: receptors.txt
>Ligands file: ligands.txt
>Config file: config.txt
>Found 0 completed receptor-ligand combinations. 1 combinations to be docked.
>  0%|                                                                                                                                                                                                                                                    | 0/1 [00:00<?, ?it/s]Docking the receptor /mnt/NAS_PROJECT/vol_Vyteam/vol_Diem/DATASM02/Docking/mutadock/2z4q.pdb to the ligand /mnt/NAS_PROJECT/vol_Vyteam/vol_Diem/DATASM02/Docking/mutadock/DB00317.sdf
>Docking for /mnt/NAS_PROJECT/vol_Vyteam/vol_Diem/DATASM02/Docking/mutadock/DB00317.sdf with /mnt/NAS_PROJECT/vol_Vyteam/vol_Diem/DATASM02/Docking/mutadock/2z4q.pdb
>Press Ctrl+D (EOFE Error) to skip this receptor-ligand combination.
>Preparing receptor /mnt/NAS_PROJECT/vol_Vyteam/vol_Diem/DATASM02/Docking/mutadock/2z4q.pdb
>  0%|                                                                                                                                                                                                                                                    | 0/1 [00:00<?, ?it/s]

Thank you very much.
Mỹ Diễm

**Comment by ddiem-ri-4D** [comment]
Hi @naisarg14 

I have resolved the issue, thank you very much for your support ^^

Mỹ Diễm
